export enum ProcedureMethodVariants {
  COMPETITIVE_SELECTION = "COMPETITIVE_SELECTION",
  REQUEST_OFFERS = "REQUEST_OFFERS",
  REQUEST_QUOTATIONS = "REQUEST_QUOTATIONS",
  CONTEST = "CONTEST",
  AUCTION = "AUCTION",
  AUCTION_LOWER = "AUCTION_LOWER",
  AUCTION_DOWN = "AUCTION_DONW",
  TWO_STAGE_AUCTION = "TWO_STAGE_AUCTION",
}

export enum ProcedureSectionVariants {
  SECTION_223_FZ = "SECTION_223_FZ",
  SECTION_COMMERCIAL_PROCEDURES = "SECTION_COMMERCIAL_PROCEDURES",
}
